### ISSUE TITLE
Use XDG spec compliant configuration directory

### ISSUE THREAD

**Issue by lbeltrame** [X0R0X/cli-torrent-dl#1]
As per the XDG spec, configuration files should land in `~/.config/`or a subdirectory under it. This makes things cleaner instead of a random hidden directory in one's $HOME.

[Pyxdg](https://pyxdg.readthedocs.io/en/latest/index.html) offers a ready module (I have no idea how heavy it is on the dependency side) to handle this without worrying about the finer details.

**Comment by X0R0X** [comment]
Thanks for the input! Fixed in  commit 5dac98b.

**Comment by ArmaanB** [comment]
This is better, but still not ideal. According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/), the program should check for the $XDG_CONFIG_HOME environment variable, and only if its unset or empty, default to ~/.config.

I think the README also needs to be updated to reflect this change.
